FROM eclipse-temurin:17-jre
RUN apt-get update && apt-get install -y --no-install-recommends curl netcat-openbsd && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY graph-service/target/quarkus-app/lib/ /app/lib/
COPY graph-service/target/quarkus-app/*.jar /app/
COPY graph-service/target/quarkus-app/app/ /app/app/
COPY graph-service/target/quarkus-app/quarkus/ /app/quarkus/
EXPOSE 9006
CMD ["java", "-jar", "quarkus-run.jar"]
