FROM eclipse-temurin:17-jre
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY api-gateway/target/quarkus-app/lib/ /app/lib/
COPY api-gateway/target/quarkus-app/*.jar /app/
COPY api-gateway/target/quarkus-app/app/ /app/app/
COPY api-gateway/target/quarkus-app/quarkus/ /app/quarkus/
EXPOSE 8080 9000
CMD ["java", "-jar", "quarkus-run.jar"]
